// global.d.ts
//
// Next.js's webpack config handles *.css imports at build time, this just
// tells the standalone TypeScript checker (npx tsc, this project's CI step)
// that the side-effect import in app/layout.tsx is a real, valid module
// rather than a missing one. next-env.d.ts is regenerated by Next and
// shouldn't be hand-edited, so this lives as its own file instead.
declare module "*.css";
