// lib/receiptPdf.ts
//
// Renders an OrderReceipt/TopupReceipt (lib/receiptService.ts) as a
// one-page PDF, via pdfkit — no headless-browser dependency, works fine
// in a serverless function (this app deploys to Vercel, README).
//
// IMPORTANT, learned the hard way earlier in this project: pdfkit's
// standard 14 fonts (Helvetica etc.) use WinAnsiEncoding, which does
// NOT include the ₦ naira sign (U+20A6) — it silently renders as a
// broken-bar glyph (¦) instead of throwing, so this is easy to ship
// without noticing. formatMoneyForPdf below is a PDF-safe variant of
// lib/money.ts's formatMoney: same Intl.NumberFormat number formatting,
// "NGN " prefix instead of the symbol. Never call formatMoney() (or use
// a literal ₦) inside this file.
import "server-only";
import PDFDocument from "pdfkit";
import { fromMinorUnits } from "./money";
import type { OrderReceipt, TopupReceipt } from "./receiptService";

function formatMoneyForPdf(minor: number): string {
  const amount = fromMinorUnits(minor);
  return `NGN ${new Intl.NumberFormat("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount)}`;
}

const INK = "#12161F";
const SUB = "#5B6472";
const LINE = "#D7DCE3";
const ACCENT = "#15803D";

function row(doc: PDFKit.PDFDocument, y: number, label: string, value: string, opts: { bold?: boolean; color?: string } = {}) {
  doc.fillColor(SUB).font("Helvetica").fontSize(10).text(label, 56, y, { width: 260 });
  doc
    .fillColor(opts.color || INK)
    .font(opts.bold ? "Helvetica-Bold" : "Helvetica")
    .fontSize(opts.bold ? 12 : 10)
    .text(value, 320, y, { width: 220, align: "right" });
}

function renderCommonHeader(doc: PDFKit.PDFDocument, kicker: string, reference: string, confirmedAt: string) {
  doc.fillColor(SUB).font("Helvetica-Bold").fontSize(9).text(kicker.toUpperCase(), 56, 56, { characterSpacing: 1 });
  doc.fillColor(INK).font("Helvetica-Bold").fontSize(22).text("Receipt", 56, 72);
  doc.fillColor(SUB).font("Helvetica").fontSize(9).text(`Reference: ${reference}`, 56, 102);
  doc.text(`Confirmed: ${new Date(confirmedAt).toLocaleString("en-NG")}`, 56, 116);
  doc.moveTo(56, 140).lineTo(539, 140).lineWidth(1).strokeColor(LINE).stroke();
}

/** Renders one receipt to a PDF buffer. pdfkit is stream-based; this
 * just collects the chunks, the caller (an API route) streams the
 * result as `application/pdf`. */
export function renderReceiptPdf(receipt: OrderReceipt | TopupReceipt): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 56 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    if (receipt.kind === "topup") {
      renderCommonHeader(doc, "SourceFi — wallet top-up", receipt.reference, receipt.confirmedAt);
      let y = 170;
      row(doc, y, "Type", "Wallet top-up");
      y += 24;
      row(doc, y, "Provider", "Yellow Card");
      y += 24;
      doc.moveTo(56, y + 8).lineTo(539, y + 8).strokeColor(LINE).stroke();
      y += 26;
      row(doc, y, "Amount credited", formatMoneyForPdf(receipt.amountMinor), { bold: true, color: ACCENT });
    } else {
      const kicker = receipt.kind === "funding" ? "SourceFi — order funded" : "SourceFi — order settled";
      renderCommonHeader(doc, kicker, receipt.providerReference || `order-${receipt.orderId}`, receipt.confirmedAt);
      let y = 170;
      row(doc, y, "Order", `${receipt.orderCode} — ${receipt.title}`);
      y += 24;
      if (receipt.buyerEmail) {
        row(doc, y, "Buyer", receipt.buyerEmail);
        y += 24;
      }
      if (receipt.supplierBusinessName) {
        row(doc, y, "Supplier", receipt.supplierBusinessName);
        y += 24;
      }
      row(doc, y, "Provider", receipt.provider);
      y += 24;
      if (receipt.txHash) {
        row(doc, y, "Transaction hash", receipt.txHash);
        y += 24;
      }
      doc.moveTo(56, y + 8).lineTo(539, y + 8).strokeColor(LINE).stroke();
      y += 26;
      row(doc, y, "Gross amount", formatMoneyForPdf(receipt.grossAmountMinor));
      y += 22;
      row(doc, y, "Platform fee", `- ${formatMoneyForPdf(receipt.platformFeeMinor)}`);
      y += 24;
      doc.moveTo(320, y).lineTo(539, y).strokeColor(LINE).stroke();
      y += 12;
      row(
        doc,
        y,
        receipt.kind === "funding" ? "Net into escrow" : "Net paid to supplier",
        formatMoneyForPdf(receipt.netAmountMinor),
        { bold: true, color: ACCENT }
      );
    }

    doc
      .fillColor(SUB)
      .font("Helvetica")
      .fontSize(8)
      .text("Generated by SourceFi. This receipt reflects the same figures shown on the order/wallet screen it was opened from.", 56, 760, {
        width: 483,
      });

    doc.end();
  });
}
